name: Android Release CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    name: Run Tests and Build Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Gradle cache
      - name: Set up Gradle Build Cache
        uses: gradle/actions/setup-gradle@v3

      # Step 3: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Decode Keystore
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Step 6: Run Instrumentation Tests on Emulator
      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -no-accel
          emulator-boot-timeout: 1800
          script: |
            adb wait-for-device
            adb shell getprop sys.boot_completed
            sleep 30
            ./gradlew connectedCheck

      # Step 7: Build Signed Release APK
      - name: Build Signed Release APK
        env:
          KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      # Step 8: Upload APK to GitHub Release
      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}-${{ github.sha }}
          name: "Release ${{ github.run_number }}"
          body: "Automated release of KotoDex TCG."
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
